import micropip

JSBEAUTIFIER_VERSION = "THIS_VALUE_SHOULD_HAVE_BEEN_FILLED_WHEN_BUNDLING_XIPLOT"
XIPLOT_WHEEL = "THIS_VALUE_SHOULD_HAVE_BEEN_FILLED_WHEN_BUNDLING_XIPLOT"

micropip.add_mock_package("jsbeautifier", JSBEAUTIFIER_VERSION)
micropip.install(["setuptools", XIPLOT_WHEEL])
