name: gh-pages

on:
  push:
    branches:
      - wasm

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check the pyodide version
        run: |
          echo "PYODIDE_SHA_SHORT=$(git submodule status pyodide | cut -c 2-8)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ./pyodide
          key: pyodide-${{ env.PYODIDE_SHA_SHORT }}-${{ hashFiles('patches/pyodide.patch') }}
          restore-keys: |
            pyodide-${{ env.PYODIDE_SHA_SHORT }}-${{ hashFiles('patches/pyodide.patch') }}
            pyodide-${{ env.PYODIDE_SHA_SHORT }}

      - name: Build the Documentation
        run: make -B deploy
      
      - name: Deploy the Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
