name: Test xiplot

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["**.py", "requirements.txt"]
  pull_request:
    branches: [main]
    paths: ["**.py", "requirements*.txt"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"] #, "3.11"] # Python 3.11 has trouble installing packages on GitHub

    steps:
      - uses: actions/checkout@v2

      - name: Set up chome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
          echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install libnss3-dev google-chrome-stable

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
          python -m pip install test_plugin/

      - name: Build package
        run: |
          python -m build .
          python -c "import os, glob; assert os.path.getsize(sorted(glob.glob('dist/slisemap-*.whl'))[-1]) > 10_000"

      - name: Test with pytest
        run: |
          pytest
